{% set name = "gridemissions" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gridemissions-{{ version }}.tar.gz
  sha256: c36988263ef128e06becd5fd0822d70e2c2d28f68e35e5ba3bff739fb4e92ba0

build:
  entry_points:
    - gridemissions_download=gridemissions.scripts.download:main
    - update_gridemissionsdata=gridemissions.scripts.update:main
    - ba_report=gridemissions.scripts.ba_report:main
    - ampd=gridemissions.scripts.ampd:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - requests
    - pandas >=2.0
    - matplotlib-base >=3.4.2

test:
  imports:
    - gridemissions
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jdechalendar/gridemissions/
  summary: Tools for power sector emissions tracking
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jdechalendar
